stan-dev/rstanarm

vignettes/binomial.Rmd
vignettes/continuous.Rmd
vignettes/count.Rmd
vignettes/pooling.Rmd
vignettes/rstanarm.Rmd

@bgoodri Aki wants to remove the weights from the `loo::compare()` output until we’ve done more work on those. This PR just removes references to the weights from the rstanarm vignettes

remove references to loo weights in vignettes

---

R/loo.R
R/posterior_linpred.R
R/posterior_predict.R
R/pp_data.R
R/stanreg-methods.R
tests/testthat/test_loo.R
tests/testthat/test_posterior_predict.R

@bgoodri can you take a look at this quickly before we merge? 
closes #109 
* Adds `offset` argument to `posterior_predict`, `posterior_linpred`, and `log_lik`
* `offset` argument is __required__ if `newdata` is specified and model was fit using an offset

Bugfix issue109 posterior predict with offset

---

exec/continuous.stan

In `continuous.stan`, for gaussian family with log link use exponentiated linear predictor with normal distribution rather than the lognormal distribution. 
@bgoodri This look right to you?

fix for gaussian(link="log")

---

R/misc.R
R/stan_glm.fit.R
exec/continuous.stan
tests/testthat/test_misc.R
tests/testthat/test_stan_glm.R

* verify outcome values match support implied by family object in `stan_glm.fit`
* add lower and upper bounds for `y` in `continuous.stan`
closes #144

Validate glm outcome support

---

R/stanjm.R

Added function to the bottom of stanjm.R that is a variation of b_names. It has the additional argument "submodel" which allows the user to only select the b parameters for longitudinal submodel M.

Include b_names function that selects b parameters for submodel M only

---

DESCRIPTION
R/loo.R
R/misc.R
R/stan_aov.R
R/stan_betareg.R
R/stan_gamm4.R
R/stan_glm.R
R/stan_glmer.R
R/stan_lm.R
R/stan_polr.R
man-roxygen/args-formula-data-subset.R
tests/testthat/test_misc.R

This PR introduces a warning if the `data` argument is not specified when fitting a model and an error if it is specified but is not a data frame.
The doc has also been updated with a warning about not specifying the data argument.
Closes #162

Warning if no data arg

---

R/print-and-summary.R
R/rstanarm-package.R
R/stan_aov.R
R/stan_betareg.R
R/stan_gamm4.R
R/stan_glm.R
R/stan_glmer.R
R/stan_lm.R
R/stan_polr.R
R/stanreg.R

Closes #169 
As reported in #169 the output from `print.stanreg` and `summary.stanreg` is a mess when a model is fit using `do.call`. This PR changes the printed output from the `print.stanreg` and `summary.stanreg` methods so that it doesn't display the actual `call` object at the top but rather just some of the info that would be included in call. 
@bgoodri @imadmali Anything you think should included beyond what I have or anything that should be removed? (See example below.)
-----
For example, now these two ways of fitting the same model
```r
fit <- stan_glmer(mpg ~ wt + (1 + wt|cyl), data = mtcars)
fit <- do.call(stan_glmer, args = list(formula = mpg ~ wt + (1 + wt|cyl), data = mtcars))
```
will result in the same output from `print` and `summary`.
The beginning of the output from …

Bugfix issue169 call

---

.travis.yml
DESCRIPTION
exec/continuous.stan
tests/testthat/test_methods.R
tests/testthat/test_misc.R
tests/testthat/test_stan_betareg.R

Cleaned up some of the code in `continuous.stan` and updated some of the tests so that they use `algorithm = "optimizing"` instead of `algorithm = "sampling"`. (Now the runtime for `devtools:tests()` is only ~5 min.)

cleanup-betareg

---

R/stan_aov.R

This pull request removes a bug in `stan_aov` that prevents the correct use of the `contrast` argument and corrects the wrong use of `contrast` in the `stan_aov`  example.
First, the argument to `contrast` needs to be a `list` (as it is passed on to `model.matrix`). A string, as used in the current example, is simply ignored. See the following, where the first is the current example, the second does not use `contrast` and produces the same results.
```
m0 <- stan_aov(yield ~ block + N*P*K, data = npk, 
contrasts = "contr.poly",
prior = R2(0.5), seed = 12345) 
m1 <- stan_aov(yield ~ block + N*P*K, data = npk,
prior = R2(0.5), seed = 12345) 
coef(m0)
coef(m1)
```
The bug is that `stan_aov` fails when passing `contrasts` in the correct manner:
```
m2 <- stan_aov(yield ~ block + N*P*K, data = …
```

stan_aov uses contrasts args correctly, corrected example

---

DESCRIPTION
R/prior_summary.R
R/stan_betareg.R
R/stan_betareg.fit.R
R/stan_gamm4.R
R/stan_glm.R
R/stan_glm.fit.R
R/stan_glmer.R
inst/NEWS
vignettes/priors.Rmd

This PR changes the default `prior_aux` from `cauchy(0, 5)` to `exponential(1)`. Auto-scaling of the aux parameter (`sigma`) is done by default for Gaussian models, but that can be turned off by specifying `autoscale=FALSE` in the call to `exponential`.

Have prior_aux default to exponential distribution

---

R/stanreg-methods.R

I was running through `VarCorr()` line by line to see how it works. When running code interactively, `else` can't start a new line. It raises an error. This edit fixes that.

move `else` statement

---

R/print-and-summary.R

For models fit with `stan_glm` and `stan_lm` only, this PR adds a line to the `print.stanreg` and `summary.stanreg` output giving the number of predictors. I've used `length(coef(object))` to count the predictors, which will count the intercept as a predictor. In the example below the number of predictors is computed to be 4: the intercept, the `wt` variable, and the two levels of `cyl` (third level is dropped because there's an intercept). 
```r
fit <- stan_glm(mpg ~ wt + factor(cyl), data = mtcars)
print(fit)
```
```
stan_glm
family:       gaussian [identity]
formula:      mpg ~ wt + factor(cyl)
observations: 32
predictors:   4
------
(rest of print output the same as before)
```
@bgoodri If Andrew prefers to use `n` and `k` instead of `observations` and `predictors` we can change it …

Print number of predictors for most single-level models

---

src/stan_files/model/assoc_evaluate.stan

The etaauc and muauc association structures had a bug which meant that the baseline hazard estimate was wrong for joint models estimated with assoc = "etaauc" or assoc = "muauc". The regression coefficients were still correct, but the error in the baseline hazard meant that survival predictions were wrong. These errors can be seen, for example, by fitting a joint model with assoc = "etaauc" and then checking posterior predictions via the ps_check() function.
The problem was that the intercept term wasn't included in the linear predictor for the longitudinal submodel when calculating the AUC for the longitudinal submodel, leading to a shift in the linear predictor for the event submodel that wasn't corrected post-estimation.
It was a simple copy and paste error, that led to a serious bug …

Fix serious bug with etaauc & muauc association structures

---

vignettes/aov.Rmd
vignettes/betareg.Rmd
vignettes/binomial.Rmd
vignettes/continuous.Rmd
vignettes/count.Rmd
vignettes/glmer.Rmd
vignettes/jm.Rmd
vignettes/lm.Rmd
vignettes/pooling.Rmd
vignettes/rstanarm.Rmd

This fixes a number of typos in the source files for the vignettes. In one or two cases, it also fixes broken links between the vignettes.

Fix typos in vignettes.

---

R/print-and-summary.R
R/stan_aov.R
R/stan_glm.fit.R
R/stan_lm.R

Separates the printing of auxiliary variables (and marks them as such) in order to distinguish them from regression coefficients in the printed output. 
```
stan_glm
family:       gaussian [identity]
formula:      mpg ~ wt + cyl
observations: 32
predictors:   3
------
Median MAD_SD
(Intercept) 39.7    1.7  
wt          -3.2    0.7  
cyl         -1.5    0.4  
Auxiliary parameter(s):
Median MAD_SD
sigma 2.6    0.4   
```
This should be clear to the user since sigma (and the other auxiliary parameters for other GLMs) are specified via `prior_aux` and are referred to as auxiliary parameters in the doc. 
Closes #284

Print aux separately

---

R/misc.R
R/posterior_linpred.R

Closes #285
As requested by @avehtari, this PR enables `posterior_linpred()` to be used for `stan_glm` models fit using optimization.

Allow posterior_linpred for optimizing

---

R/posterior_traj.R

An element in the object returned by `ggplot_build` was renamed in ggplot2 v3.3.0, causing an error in `plot.predict.stanjm` when plotting multiple facets. This should hopefully fix it.
Closes #311.

Fix small bug in plot.predict.stanjm

---

R/jm_data_block.R
R/prior_summary.R
R/stan_jm.fit.R

Some aspects of the `lkj()` prior were not getting returned in the `prior.info` element of stan_jm/mvmer objects. They should be included now. The printing of the `lkj()` when `prior_summary` is called should now be more comprehensive; before it was missing the adjusted scales and df for the student-t component of the `lkj()` prior (i.e. the student-t prior on the SDs of the random effects).
The `stan_mvmer` objects also needed a small fix. The elements of their `prior.info` were named "priorLong", "priorLong_intercept", etc, as in joint models. I needed to remove the "Long" from these names so that they printed correctly when `prior_summary()` was called on a `stan_mvmer` object.

Tidy up prior_summary for stan_jm and stan_mvmer

---

R/jm_data_block.R

This function is intended to substitute predvars into the model formula. The use of grep was a bit of a hack, and didn't carry through some of the list names. Hopefully the use of deparse works better (it seems to anyway).

Improve the handling of predvars

---

R/print-and-summary.R
R/stan_glm.R
R/stan_glm.fit.R
src/stan_files/bernoulli.stan
src/stan_files/binomial.stan
src/stan_files/continuous.stan
src/stan_files/count.stan
src/stan_files/data/data_glm.stan

closes #283 
@avehtari @bgoodri 
This PR adds a `mean_PPD` argument to `stan_glm` that defaults to `TRUE` except when `algorithm="optimizing"`:
```r
stan_glm(..., mean_PPD = algorithm != "optimizing")
```
The `print.stanreg` method has also been updated to not print `mean_PPD` information if `mean_PPD` was set to `FALSE` when fitting the model. 
In the Stan files used for `stan_glm` a `compute_mean_PPD` flag has been added to the data block via the `data_glm` chunk
```stan
int<lower=0,upper=1> compute_mean_PPD;  // 1 = yes
```
and then in `generated quantities` 
```stan
real mean_PPD = compute_mean_PPD ? 0 : negative_infinity();
...  
if (compute_mean_PPD) {
...
}
```

mean_PPD argument for stan_glm

---

R/stan_jm.R

Two options were described as default in the basehaz parameter, I corrected this to the one fitting the function definition and description in the details section.

stan_jm: possible copy-paste error in dokumentation

---

R/loo.R

Fix kfold to work if folds are given but the number of folds in folds is different from 10 (the default value for K in kfold function)

fix kfold to work when folds given and K!=10

---

R/stan_glm.fit.R

@bgoodri I think this fixes the bug reported by @wds15 in #328. We needed to add some more as.array calls in order to match dimensions declared in the stan program.  
closes #328

stan_glm.fit: fix for if only 1 zero in binomial data

---

R/zzz.R

Closes #257
Reflects changes to `bayesplot` approach to themes in stan-dev/bayesplot#149

Remove theme_set() on startup and change message

---

R/nsamples

This is a short and convenient wrappter to extract the number of samples, similar to what @paul-buerkner has implemented in _brms_ (https://github.com/paul-buerkner/brms/blob/master/R/generics.R).
The generic and the _brmsfit_-methods are both in the package _brms_, but maybe it would make sense to move the generic to _rstantools_?

Function "nsamples()" for stanreg models

---

src/stan_files/continuous.stan

OLS trick works also for stan_gamm4 with smooths when `len_y >= (has_intercept + K + K_smooth)`. `S` is appended to `X_` and `beta_smooth` is appended to coeff vector, and that's all! Significant speedup is obtained when applicable.

do OLS if K_smooth > 0

---

R/stan_glm.fit.R

- passes importance_resampling option to rstan
- computes Pareto diagnostic and resampling only if enabled
this will make it possible to avoid possibly costly log_p computation for approximate posterior draws

pass and check importance_resampling option

---

R/misc.R
R/stan_betareg.R
R/stan_biglm.fit.R
R/stan_glm.R
R/stan_glm.fit.R
R/stan_glmer.R
R/stan_lm.fit.R
R/stan_nlmer.R

closes #337
This PR allows formulas with no LHS when `prior_PD=TRUE`. This is implemented for `stan_glm`, `stan_[g]lmer`, and `stan_lm` only (although I don't think it makes as much sense for `stan_lm` given the prior). 
It does this by generating fake outcome variables which allows the Stan code to run (it needs N values of y even if not conditioning on them). 
For Gaussian models the fake outcome has SD of 1, which essentially disables prior autoscaling even if autoscale is left at TRUE. Because the default priors do autoscaling,  it therefore matters whether y is specified or not when `prior_PD=TRUE` unless autoscale=FALSE for all priors (including intercept and aux). 
These give different results because of the default prior autoscaling:
```r
fit1 <- stan_glm( ~ wt + qsec + am, data = …
```

Don't require LHS of formula if prior_PD=TRUE (for some modeling functions)

---

R/misc.R
src/stan_files/bernoulli.stan

This PR makes it possible to fit bernoulli models with stan_glm and and stan_glmer where the outcome is all zeros or all ones, e.g. 
```r
d <- data.frame(y = rep(0, 50))
fit <- stan_glm(y ~ 1, data = d, family = "binomial")
```
I had to modify the data block of the Stan program to not require `lower=1`, but as far as I can tell that's the only line of the Stan program that needed changing?

allow all zeros or all ones with bernoulli

---

R/bayes_R2.R

This closes #376, fixing a bug introduced in 9ff7f71.
Note that there exist no tests for any of these functions, and the handling of `y` in the binomial case is slightly different in `loo_R2`, where it's also checked if it's a factor.

Fix bug in bayes_R2() for binomial family with bernoulli trials

---

R/posterior_vs_prior.R

This allows the following examples to run as expected (see #383):
```
x = rnorm(100)
y = rpois(100, exp(x))
d = data.frame(x = x, y = y)
glm_4000_2000 <- stan_glm(y ~ x, data = d, iter = 4000, warmup = 2000)
posterior_vs_prior(glm_4000_2000)
glm_6000_3000 <- stan_glm(y ~ x, data = d, iter = 6000, warmup = 3000)
posterior_vs_prior(glm_6000_3000)
```

Remove hardcoded number of iterations in posterior_vs_prior()

---

R/bayes_R2.R

This allows two calls to loo_R2() on the same fitted object to produce identical results, without affecting the state of the RNG outside of the function. This fixes #378.

Set the random seed before calling rexp() in loo_R2()

---

R/priors.R

Fix documentation of default degrees of freedom for hs() and hs_plus()

---

DESCRIPTION
src/stan_files/bernoulli.stan
src/stan_files/continuous.stan
src/stan_files/count.stan

This PR adds the condition `K != 0` when checking whether to use Stan's compound glm functions. This fixes #396 but we can go back to allowing it for `K == 0` when https://github.com/stan-dev/math/issues/1398 is fixed in Stan math and included in rstan. 
I also included a commit that bumps the rstanarm version number up to 2.19.3. I think we should submit this to CRAN right away if possible with a comment apologizing for the quick turnaround. It should get through quickly given that it's the only change since they accepted 2.19.2.

Bugfix for glms with only intercept

---

R/misc.R

Modify `drop_redundant_dims` to avoid an error when data is a data.table, as reported in #431. This happens because `drop_redundant_dims` indexes into a data.frame using a vector of logicals, but data.table expects an unquoted name to be a column name. To fix this, my code skips the dimension-reduction step if data is a data.table.
This shouldn't cause problems with data.table: In general, dimension reduction like this isn't necessary for a data.table, because data.table makes it really difficult to add a matrix as a column. The only way to do this is to explicitly coerce an existing data.frame that has matrices as columns using `setDT()`, and that will warn the user against doing this (see https://github.com/Rdatatable/data.table/pull/3851). For any other case, data.table will …

Fix #431: Make drop_redundant_dims safe for data.table

---

R/stan_glm.R
tests/testthat/test_stan_glm.R

closes #444 
closes #445
@bgoodri This fixes an important bug reported by @rvlenth. It turns out the same problem was causing both #444 and #445.
The fix is to make sure `contrasts` info isn't accidentally dropped when subsetting the model matrix. 
This now gives correct results: 
```r
contrasts <- list(wool = "contr.sum", tension = "contr.sum")
fit <-  stan_glm(breaks ~ wool * tension, data = warpbreaks,
contrasts = contrasts, chains = 1, refresh = 0)
```
```
> fit$contrasts
$wool
[1] "contr.sum"
$tension
[1] "contr.sum"
```
```
> predict(fit, newdata = warpbreaks[1:3, ])
1        2        3 
44.55111 44.55111 44.55111 
```
```
> model.matrix(fit)
(Intercept) wool1 tension1 tension2 wool1:tension1 wool1:tension2
1            1     1        1        0              1              0
2 …
```

fix incorrect handling of contrasts in stan_glm

---

DESCRIPTION
vignettes/ab-testing.Rmd

I'd like to contribute a vignette that outlines how to do A/B testing inference (post-experiment) with rstanarm functions. As discussed [here](https://github.com/stan-dev/stan-dev.github.io/pull/97) I think it would be useful if it was part of the "Additional tutorials on specific modeling techniques and applications" section on the [vignette page](https://mc-stan.org/rstanarm/articles/index.html) of the rstanarm site. @jgabry I've left your comments in and have changed the content based on some of them. Also, regarding _Appendix B_, I don't fully understand how priors are specified on group specific intercepts when using `stan_glmer` so I just said something to the effect of "default priors are used".

Adding ab-testing vignette

---

NEWS.md
R/loo-kfold.R
tests/testthat/test_loo.R

closes #460
Computes `p_kfold` and `se_p_kfold`, which were previously `NA`. 
```r
fit <- stan_glm(mpg ~ wt + am, data = mtcars)
kfold(fit, K = 10)
Based on 10-fold cross-validation
Estimate  SE
elpd_kfold    -84.6 4.2
p_kfold         4.2 1.2
kfoldic       169.3 8.4
```

Compute effective number of parameters for K-fold CV

---

R/misc.R

fixes #491
This PR avoids performing one of the checks on `newdata` that resulted in an error if `newdata` had 0 columns. Allowing 0-column `newdata` is useful for doing `posterior_predict()` for intercept only models, as pointed out in #491  by @davidkane9. With this change, the following now works: 
```r
fit <- stan_glm(mpg ~ 1, data = mtcars)
posterior_predict(fit, newdata = tibble::tibble(.rows = 1)) # generate predictions for 1 obs
posterior_predict(fit, newdata = tibble::tibble(.rows = 2)) # generate predictions for 2 obs
...
```

Allow 0-column newdata if positive number of rows

---

README.md

Adds README instructions for how to install the binary for the development version with `stan_surv` functionality. As requested in this forum post: https://discourse.mc-stan.org/t/rstanarm-cran-vs-development-version-installation-issues/14399/45

Add survival version to README installation instructions

---

README.md

As experienced over in #512, users can run out of RAM when installing `rstanarm` from source with the recommended `-j4`. This drops the recommended number to 2 and adds a warning

Reduce recommended cores for makeflags during install

---

src/stan_files/data/data_assoc.stan

fixes #516
Thanks to @sambrilleman this fixes a dimension mismatch error when combining an offset with `assoc` when using `stan_jm`.

data_assoc.stan: fix dimension for offset

---

NEWS.md
R/stan_clogit.R
tests/testthat/test_stan_clogit.R

closes #519
Previously the model would fit but would error in some post-processing step where it didn't like factors. This PR just converts a factor to a binary variable before fitting the model.

stan_clogit: allow y to be a factor

---

R/stan_glm.fit.R
tests/testthat/test_stan_glmer.R
tests/testthat/test_stan_jm.R
tests/testthat/test_stan_mvmer.R

fixes #341
This affects models using `stan_glm.fit` as well as `stan_jm` and `stan_mvmer`, which use the same internal `validate_glm_outcome_support` that `stan_glm.fit` does. 
Previous error message: 
```
f1 <- stan_lmer(formula = as.character(logBili) ~ 1 + (1 | id), 
data = pbcLong, 
chains = 1)
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
Exception: variable does not exist; processing stage=data initialization; variable name=y; base type=vector_d  (in 'model_continuous' at line 32)
In addition: Warning message:
In FUN(X[[i]], ...) : data with name y is not numeric and not used
failed to create the sampler; sampling not done
Error in check_stanfit(stanfit) : 
Invalid stanfit object produced please report bug
Error in dimnamesGets(x, value) : 
invalid dimnames …
```

error earlier if outcome is character

---

R/misc.R
R/posterior_survfit.R

Fixes #458 on the `feature/survival` branch. So that passing `newdataEvent` or `newdataLong` to stan_surv post-estimation functions throws an error, and passing `newdataEvent` to stan_jm post-estimation functions throws an error.
Also ensures that a `stan_surv` model with group specific parameters is returned as TRUE for `is.mer()`. Can't remember exactly what that fix was for, but I'm guessing to ensure some post-estimation extraction functions related to random effects work (maybe `ranef()` or something similar).

Improve error msg when incorrect newdata argument is passed to stan_surv/stan_jm

---

vignettes/surv.Rmd

This adds details to the `stan_surv` vignette, so that it aligns with the [arXiv paper](https://arxiv.org/pdf/2002.09633.pdf).

Updates stan_surv vignette to align with arXiv paper

---

DESCRIPTION
R/doc-rstanarm-package.R
R/stan_betareg.R
R/stan_biglm.R
R/stan_clogit.R
R/stan_gamm4.R
R/stan_glm.R
R/stan_glmer.R
R/stan_jm.R
R/stan_lm.R
R/stan_mvmer.R
R/stan_nlmer.R
R/stan_polr.R

@bgoodri This removes all the `'px'` uses with the Stan logo that CRAN complained about.

remove 'px' as CRAN requested

---

inst/include/CODOLS.hpp
inst/include/meta_header.hpp
src/stan_files/continuous.stan
tests/testthat/test_stan_glm.R

use COD to create sufficient statistic

---

R/stan_gamm4.R
tests/testthat/test_stan_glmer.R

fixes #288
Throw an error if no smooth terms instead of letting `mgcv::jagam` throw some jibberish error message.

stan_gamm4: error if no smooth terms

---

R/print-and-summary.R
tests/testthat/test_methods.R

fixes #411
If `subset` is specified the print and summary output now include it. A few examples: 
```
> stan_glm(mpg ~ wt + cyl, data = mtcars, subset = rep(TRUE, 32))
stan_glm
family:       gaussian [identity]
formula:      mpg ~ wt + cyl
observations: 32
predictors:   3
subset:       rep(TRUE, 32)
...
```
```
> stan_glm(mpg ~ wt + am, data = mtcars, subset = cyl == 4)
stan_glm
family:       gaussian [identity]
formula:      mpg ~ wt + am
observations: 11
predictors:   3
subset:       cyl == 4
...
```

include 'subset' info in print output

---

R/stan_betareg.fit.R
R/stan_glm.fit.R
tests/testthat/test_misc.R
tests/testthat/test_stan_betareg.R
tests/testthat/test_stan_glm.R

fixes #469
Only recommends QR=TRUE for variational inference if there are at least 2 predictors. Previously we were recommending it also for 1 predictor but it would then error if the user tried that.

don't recommend QR if not enough predictors

---

R/doc-datasets.R

While lecturing this week on binomial regression I was showcasing the `wells` dataset (Gelman & Hill, 2007) and found an incosistency.
In the help pane the variable was named as `association` but it is only `assoc`.
```r
r$> names(wells)
[1] "switch"  "arsenic" "dist"    "assoc"   "educ"
```

wells dataset wrong variable name

---

R/pp_data.R
R/stanreg-methods.R

Address #535 by reversing the order of checks for type in both `model.frame.stanreg` and `formula.stanreg`. 
Note: this breaks behavior of `ranef()`, when applied to a stan_surv model with frailty.

stan_surv: Error when including frailty terms

---

R/stan_surv.R

Changes introduced in R>=4.3 mean that the `||` operator returns an error when it is used to evaluate an or condition for a length > 1 vector. The fix here is to instead use the vectorised form, `|` (which probably should have been used in the first place...).
Fixes #593.

Use | instead of || for or condition

---

dev-notes/rstanarm_dev_notes.md
src/stan_files/functions/SSfunctions.stan
src/stan_files/functions/bernoulli_likelihoods.stan
src/stan_files/lm.stan
src/stan_files/polr.stan

There are still some pieces of deprecated syntax in the rstanarm Stan models which will cause failures under 2.33:
- Forward declarations of Stan functions
- `fabs` deprecated in favour of `abs`
- `_cdf()` functions without `|` notation
- Bug in 2.26 parser does not accept `cdf` functions *with* the `|` notation, so I've changed these to use the respective `_lcdf` function for compatibility with both

Update more deprecated syntax

---

src/stan_files/lm.stan
src/stan_files/polr.stan
tests/testthat/test_stan_lm.R
tests/testthat/test_stan_polr.R

fixes #603
The unit_vector isn't actually used anywhere in the situation when it errors (when K isn't >1) so we just make it size 2 in that case to avoid Stan's error for 1-D unit vectors. 
I also added tests for stan_lm and stan_polr to check that they now run with 1 predictor.

avoid error for 1-D unit_vector

---

tests/testthat/test_methods.R

I'm not sure exactly how this test is passing now, but AFAICT the intent is to match `{n} (posterior sample size)` where `n` is the result of the `posterior_sample_size()` call.
Something like, `...` is swallowing the `"(...)"` string and the test passes because `500` is matched.

Fix mistaken ')' alignment in output test
